# Generated by Django 4.2.16 on 2024-11-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_delete_opentestpage_alter_tag_shipment'),
        ('shipment', '0002_shipmentdetail_id_remove_shipmentdetail_batches_and_more'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_shipments', to='shipment.shipmentdetail'),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
