# Generated by Django 4.2.16 on 2024-11-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipment_detail', serialize=False, to='batch.shipment')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('truck', models.CharField(max_length=100)),
                ('batches', models.ManyToManyField(related_name='shipment_batches', to='batch.batch')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_emps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
